### ISSUE TITLE
Bug, only one blog per path

### ISSUE THREAD

**Issue by breck7** [breck7/brecksblog#1]
The path routing needs to be better.

If you have a blog at domain.com then add a blog at domain.com/blog2/

it won't work.

Need to fix the controller, possibly .htaccess.

**Comment by tylerhcarter** [comment]
Adding this line at the top of controller:

$path = str_replace(dirname($_SERVER['PHP_SELF']), "", $_GET['r']);

Should give you the correct path in $path. I haven't checked efficiency or anything though. You can find the full fix in my fork.
